experiment:
  name: DINO_Fusion_DefDETR_baseline
  group: DINO_Investigation
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  search: grid

parameters:
  seed: &seed [42]
  task: [detection]

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    val_image_log_frequency: [50]

  train:
    max_epochs: [20]
    compile: [False]
    initial_lr: [0.00002]
    backbone_lr: [0.00001]
    optimizer: [AdamW]
    watch_metric: [map]
    gradient_clip_norm: [0.1]
    gradient_accumulation_steps: [4]
    early_stopping_patience: [5]
    scheduler:
      type: [cosine]
      num_warmup_steps: [200]
      step_moment: [batch]

  loss:

  model:
    name: [fusion_dino_defdetr]
    params:
      id2label:
        0: [person]
      threshold: [0.01]
      num_feature_levels: [4]
      use_fam: [false]
      freeze_fam: [false]
      ir_dropout_rate: [0.0]
      spatial_jitter_std: [0.0]
      num_dn_groups: [5]
      label_noise_prob: [0.5]
      box_noise_scale: [1.0]
      cdn_loss_coef: [1.0]

  dataset:
    name: [wisard]
    root: [dataset/WiSARD]
    preprocessor:
      path: ["SenseTime/deformable-detr"]
    folders: [vis_ir]
    single_class: [true]
    modal_dropout: [true]
    modal_dropout_probs: [[0.2, 0.2, 0.6]]
    use_tiling: [false]

  dataloader:
    num_workers: [4]
    batch_size: [1]

  val_evaluation:
    metrics:

other_grids: