experiment:
  name: RTDETR_Final_Evaluation_Grid_CMX
  group: RTDETR_Investigation
  continue_with_errors: False
  search: grid

parameters:
  seed: &seed [42]
  task: [detection]

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    val_image_log_frequency: [50] 
    tags: [[FinalReport]]

  model:
    name: [fusion_rtdetr_cmx]
    params:
      id2label:
        0: [person]
      # TESTIAMO SOGLIE MOLTO BASSE PER VEDERE IL VERO POTENZIALE
      threshold: [0.01, 0.02, 0.05, 0.1] 
      pretrained_path: ["checkpoints/fusion_rtdetr_cmx_best.safetensors"]

  dataset:
    name: [wisard]
    root: [dataset/WiSARD]
    preprocessor:
      path: ["PekingU/rtdetr_r50vd"]
    # CONFRONTO MODALITÀ (Fondamentale per la tua tesi)
    folders: [vis, ir, vis_ir] 
    single_class: [true]

  dataloader:
    num_workers: [4]
    batch_size: [1]

  val_evaluation:
    metrics:

other_grids: []