experiment:
  name: RTDETR_Final_Evaluation_Grid_CMX
  group: RTDETR_Investigation
  continue_with_errors: False
  search: grid

parameters:
  seed: &seed [42]
  task: [detection]

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    val_image_log_frequency: [50] # Logghiamo ogni immagine per vedere bene le box
    tags: [[FinalReport]]

  model:
    name: [fusion_rtdetr_cmx]
    params:
      id2label:
        0: [person]
      # Usiamo una soglia bassa ma non estrema per vedere se il mAP si conferma
      threshold: [0.1]
      # IL PERCORSO DEL TUO MIGLIOR MODELLO
      pretrained_path: ["checkpoints/fusion_rtdetr_cmx_best.safetensors"] 

  dataset:
    name: [wisard]
    root: [dataset/WiSARD]
    preprocessor:
      path: ["PekingU/rtdetr_r50vd"]
    # Testiamo solo sulla modalità FUSION sincronizzata (la più completa)
    folders: [vis_ir] 
    single_class: [true]
    use_tiling: [false]  # Disabilitiamo il tiling per questa valutazione finale

  dataloader:
    num_workers: [8]
    batch_size: [12]

  val_evaluation:
    metrics:

other_grids: []