experiment:
  name: Thesis_RTDETR_Ablation_FAM_SSJ
  group: Thesis_RTDETR_Ablation
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  search: grid
  isolate_runs: true

parameters:
  seed: [40, 41, 42, 43, 44]
  task: [detection]

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    val_image_log_frequency: [50]
    tags: [[Thesis, RTDETR, Ablation, FAM_SSJ]]

  train:
    max_epochs: [10]
    compile: [False]
    initial_lr: [0.00002]
    optimizer: [AdamW]
    watch_metric: [map]

  loss:

  model:
    name: [fusion_rtdetr]
    params:
      id2label:
        0: [person]
      threshold: [0.01]
      use_fam: [true]
      fam_variant: [current_dcnv2]
      freeze_fam: [false]
      ir_dropout_rate: [0.0]
      spatial_jitter_std: [0.5]

  dataset:
    name: [wisard]
    root: [dataset/WiSARD]
    preprocessor:
      path: ["PekingU/rtdetr_r50vd"]
    folders: [vis_ir]
    single_class: [true]
    modal_dropout: [true]
    modal_dropout_probs: [[0.2, 0.2, 0.6]]
    use_tiling: [false]

  dataloader:
    num_workers: [8]
    batch_size: [4]

  val_evaluation:
    metrics:

other_grids: []
